name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Go Lint
        uses: dagger/dagger-for-github@b81317a976cb7f7125469707321849737cd1b3bc # v7
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: lint --source=.

      - name: Run Frontend Lint
        uses: dagger/dagger-for-github@b81317a976cb7f7125469707321849737cd1b3bc # v7
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: lint-frontend --source=.

      - name: Run Typecheck
        uses: dagger/dagger-for-github@b81317a976cb7f7125469707321849737cd1b3bc # v7
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: typecheck --source=.

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Tests
        uses: dagger/dagger-for-github@b81317a976cb7f7125469707321849737cd1b3bc # v7
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: test --source=.

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Build
        uses: dagger/dagger-for-github@b81317a976cb7f7125469707321849737cd1b3bc # v7
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: build --source=.
